spring:
  #邮箱信息
  mail:
    host: smtp.163.com
    username:
    password:
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
  security:
    filter:
      order: -100
    jwt:
      key: coderzijunNB
      expire: 3
  # 数据源信息
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/
#文件配置路径
uploadFile:
  path: C:/Users/13919/Desktop/Project/JavaWeb/myWebsite/resource/upload/
  maxSize: 50