spring:
  mail:
    host: smtp.163.com
    username: codezijun@163.com
    password: DXNLMLRGVVYKNGFM
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
  security:
    filter:
      order: -100
    jwt:
      key: coderzijunNB
      expire: 3
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: LZJ20040112
    driver-class-name: com.mysql.cj.jdbc.Driver